### ISSUE TITLE
Journal Name disappears during editing of dataset even when Journal Name (publicationName) is present in Activity Log metadata

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#785]
**Bug description:** When editing a dataset, the journal name is blank even though it was once entered and stored as shown in the Activity Log metadata. The Manuscript number is appearing however.

**Steps to reproduce:**
Check the Activity Log of a submitted dataset, see if a journal name is in the "Internal Data" section
Now go back to the dashboard page and Edit a dataset 
Look at the Journal Name form field, see that it is empty
Add the journal name back in, it does seem to save it
Submit

**Expected behavior:**
If there is a journal name (publicationName) in the Activity Log's Internal Data, expect to see whatever data is recorded there to be in the Journal Name field in the dataset form

**Attachment**
15 second screen capture using quicktime 
[Screen Recording 2020-07-14 at 3.09.54 PM.mov.zip](https://github.com/CDL-Dryad/dryad-product-roadmap/files/4927826/Screen.Recording.2020-07-14.at.3.09.54.PM.mov.zip)

**Comment by LoriEP** [comment]
This never went into the backlog. I have now updated the appropriate board. My apologies.

**Comment by ryscher** [comment]
I believe this issue has been fixed by updates since the issue was originally filed. I was unable to recreate the problem.

But thanks for the detailed description and screen capture! They were useful to verify that I was doing the actions that originally caused the problem.

**Comment by LoriEP** [comment]
@ryscher we are still seeing this... example doi: 10.25338/B8WS6R should I create a new ticket?

**Comment by ryscher** [comment]
I'll just move this back into the backlog...

**Comment by ryscher** [comment]
I believe this is related to #1159, and will be fixed with the next Dryad release. 

Now that I look back, for the dataset that originally inspired the ticket, doi:10.5061/dryad.00000000r, there was again a mismatch between the journal title and the stored ISSN, so I removed the offending ISSN. In this case, the ISSN was for a journal previously unknown to Dryad. A reminder -- we do not currently have a system for creating new journals within v2 Dryad. The procedure was supposed to be for curators to create/update the journals in the v1 system and I would migrate them, but I don't believe this has ever happened.

**Comment by ryscher** [comment]
For reference, the system to create new journals within v2 is #704
