### ISSUE TITLE
Author reports missing dataset originally archived in 2011

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#819]
**Bug description:**
Dataset DOI: 10.5061/dryad.1926 (Title: "Echinoderm phylogeny including Xyloplax, a progenetic asteroid") was archived in 2011 per author but is now no longer archived in Dryad per a title search and a DOI search

**Steps to reproduce:**
Search for the dataset, no records appear

**Expected behavior: **
Dataset record should appear 

**Note:** This dataset was a supplement to DOI: 10.1093/sysbio/syr044 and is mentioned in the article.

**Comment by ryscher** [comment]
Fixed. Migrated item from the v1 server. It is now published.

**Comment by LoriEP** [comment]
Thank you Ryan. However, I still cannot see this on a search in Dryad.

**Comment by ryscher** [comment]
Sorry about that. It's searchable now.
